// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: mediapipe/framework/stream_handler.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Akihabara.Framework.Protobuf {

  /// <summary>Holder for reflection information generated from mediapipe/framework/stream_handler.proto</summary>
  public static partial class StreamHandlerReflection {

    #region Descriptor
    /// <summary>File descriptor for mediapipe/framework/stream_handler.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StreamHandlerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihtZWRpYXBpcGUvZnJhbWV3b3JrL3N0cmVhbV9oYW5kbGVyLnByb3RvEhxh",
            "a2loYWJhcmEuZnJhbWV3b3JrLnByb3RvYnVmGittZWRpYXBpcGUvZnJhbWV3",
            "b3JrL21lZGlhcGlwZV9vcHRpb25zLnByb3RvIpQBChhJbnB1dFN0cmVhbUhh",
            "bmRsZXJDb25maWcSNwoUaW5wdXRfc3RyZWFtX2hhbmRsZXIYASABKAk6GURl",
            "ZmF1bHRJbnB1dFN0cmVhbUhhbmRsZXISPwoHb3B0aW9ucxgDIAEoCzIuLmFr",
            "aWhhYmFyYS5mcmFtZXdvcmsucHJvdG9idWYuTWVkaWFQaXBlT3B0aW9ucyKy",
            "AQoZT3V0cHV0U3RyZWFtSGFuZGxlckNvbmZpZxI5ChVvdXRwdXRfc3RyZWFt",
            "X2hhbmRsZXIYASABKAk6GkluT3JkZXJPdXRwdXRTdHJlYW1IYW5kbGVyEhkK",
            "EWlucHV0X3NpZGVfcGFja2V0GAIgAygJEj8KB29wdGlvbnMYAyABKAsyLi5h",
            "a2loYWJhcmEuZnJhbWV3b3JrLnByb3RvYnVmLk1lZGlhUGlwZU9wdGlvbnNC",
            "PAoaY29tLmdvb2dsZS5tZWRpYXBpcGUucHJvdG9CElN0cmVhbUhhbmRsZXJQ",
            "cm90b6ICCU1lZGlhUGlwZQ=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Akihabara.Framework.Protobuf.MediapipeOptionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Akihabara.Framework.Protobuf.InputStreamHandlerConfig), global::Akihabara.Framework.Protobuf.InputStreamHandlerConfig.Parser, new[]{ "InputStreamHandler", "Options" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akihabara.Framework.Protobuf.OutputStreamHandlerConfig), global::Akihabara.Framework.Protobuf.OutputStreamHandlerConfig.Parser, new[]{ "OutputStreamHandler", "InputSidePacket", "Options" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Settings specifying an input stream handler.
  /// </summary>
  public sealed partial class InputStreamHandlerConfig : pb::IMessage<InputStreamHandlerConfig> {
    private static readonly pb::MessageParser<InputStreamHandlerConfig> _parser = new pb::MessageParser<InputStreamHandlerConfig>(() => new InputStreamHandlerConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<InputStreamHandlerConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akihabara.Framework.Protobuf.StreamHandlerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InputStreamHandlerConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InputStreamHandlerConfig(InputStreamHandlerConfig other) : this() {
      inputStreamHandler_ = other.inputStreamHandler_;
      options_ = other.HasOptions ? other.options_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public InputStreamHandlerConfig Clone() {
      return new InputStreamHandlerConfig(this);
    }

    /// <summary>Field number for the "input_stream_handler" field.</summary>
    public const int InputStreamHandlerFieldNumber = 1;
    private readonly static string InputStreamHandlerDefaultValue = global::System.Text.Encoding.UTF8.GetString(global::System.Convert.FromBase64String("RGVmYXVsdElucHV0U3RyZWFtSGFuZGxlcg=="), 0, 25);

    private string inputStreamHandler_;
    /// <summary>
    /// Name of the registered input stream handler class.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string InputStreamHandler {
      get { return inputStreamHandler_ ?? InputStreamHandlerDefaultValue; }
      set {
        inputStreamHandler_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "input_stream_handler" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasInputStreamHandler {
      get { return inputStreamHandler_ != null; }
    }
    /// <summary>Clears the value of the "input_stream_handler" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearInputStreamHandler() {
      inputStreamHandler_ = null;
    }

    /// <summary>Field number for the "options" field.</summary>
    public const int OptionsFieldNumber = 3;
    private global::Akihabara.Framework.Protobuf.MediaPipeOptions options_;
    /// <summary>
    /// Options for the input stream handler.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akihabara.Framework.Protobuf.MediaPipeOptions Options {
      get { return options_; }
      set {
        options_ = value;
      }
    }
    /// <summary>Gets whether the options field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOptions {
      get { return options_ != null; }
    }
    /// <summary>Clears the value of the options field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOptions() {
      options_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as InputStreamHandlerConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(InputStreamHandlerConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InputStreamHandler != other.InputStreamHandler) return false;
      if (!object.Equals(Options, other.Options)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasInputStreamHandler) hash ^= InputStreamHandler.GetHashCode();
      if (HasOptions) hash ^= Options.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasInputStreamHandler) {
        output.WriteRawTag(10);
        output.WriteString(InputStreamHandler);
      }
      if (HasOptions) {
        output.WriteRawTag(26);
        output.WriteMessage(Options);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasInputStreamHandler) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InputStreamHandler);
      }
      if (HasOptions) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Options);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(InputStreamHandlerConfig other) {
      if (other == null) {
        return;
      }
      if (other.HasInputStreamHandler) {
        InputStreamHandler = other.InputStreamHandler;
      }
      if (other.HasOptions) {
        if (!HasOptions) {
          Options = new global::Akihabara.Framework.Protobuf.MediaPipeOptions();
        }
        Options.MergeFrom(other.Options);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            InputStreamHandler = input.ReadString();
            break;
          }
          case 26: {
            if (!HasOptions) {
              Options = new global::Akihabara.Framework.Protobuf.MediaPipeOptions();
            }
            input.ReadMessage(Options);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Settings specifying an output stream handler.
  /// </summary>
  public sealed partial class OutputStreamHandlerConfig : pb::IMessage<OutputStreamHandlerConfig> {
    private static readonly pb::MessageParser<OutputStreamHandlerConfig> _parser = new pb::MessageParser<OutputStreamHandlerConfig>(() => new OutputStreamHandlerConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OutputStreamHandlerConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akihabara.Framework.Protobuf.StreamHandlerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutputStreamHandlerConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutputStreamHandlerConfig(OutputStreamHandlerConfig other) : this() {
      outputStreamHandler_ = other.outputStreamHandler_;
      inputSidePacket_ = other.inputSidePacket_.Clone();
      options_ = other.HasOptions ? other.options_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OutputStreamHandlerConfig Clone() {
      return new OutputStreamHandlerConfig(this);
    }

    /// <summary>Field number for the "output_stream_handler" field.</summary>
    public const int OutputStreamHandlerFieldNumber = 1;
    private readonly static string OutputStreamHandlerDefaultValue = global::System.Text.Encoding.UTF8.GetString(global::System.Convert.FromBase64String("SW5PcmRlck91dHB1dFN0cmVhbUhhbmRsZXI="), 0, 26);

    private string outputStreamHandler_;
    /// <summary>
    /// Name of the registered output stream handler class.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OutputStreamHandler {
      get { return outputStreamHandler_ ?? OutputStreamHandlerDefaultValue; }
      set {
        outputStreamHandler_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "output_stream_handler" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOutputStreamHandler {
      get { return outputStreamHandler_ != null; }
    }
    /// <summary>Clears the value of the "output_stream_handler" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOutputStreamHandler() {
      outputStreamHandler_ = null;
    }

    /// <summary>Field number for the "input_side_packet" field.</summary>
    public const int InputSidePacketFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_inputSidePacket_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> inputSidePacket_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Names of the input side packets for the handler specifically and distinct
    /// from the side packets for the calculator (but could be shared).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> InputSidePacket {
      get { return inputSidePacket_; }
    }

    /// <summary>Field number for the "options" field.</summary>
    public const int OptionsFieldNumber = 3;
    private global::Akihabara.Framework.Protobuf.MediaPipeOptions options_;
    /// <summary>
    /// Options for the output stream handler.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akihabara.Framework.Protobuf.MediaPipeOptions Options {
      get { return options_; }
      set {
        options_ = value;
      }
    }
    /// <summary>Gets whether the options field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOptions {
      get { return options_ != null; }
    }
    /// <summary>Clears the value of the options field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOptions() {
      options_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OutputStreamHandlerConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OutputStreamHandlerConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OutputStreamHandler != other.OutputStreamHandler) return false;
      if(!inputSidePacket_.Equals(other.inputSidePacket_)) return false;
      if (!object.Equals(Options, other.Options)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOutputStreamHandler) hash ^= OutputStreamHandler.GetHashCode();
      hash ^= inputSidePacket_.GetHashCode();
      if (HasOptions) hash ^= Options.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasOutputStreamHandler) {
        output.WriteRawTag(10);
        output.WriteString(OutputStreamHandler);
      }
      inputSidePacket_.WriteTo(output, _repeated_inputSidePacket_codec);
      if (HasOptions) {
        output.WriteRawTag(26);
        output.WriteMessage(Options);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasOutputStreamHandler) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OutputStreamHandler);
      }
      size += inputSidePacket_.CalculateSize(_repeated_inputSidePacket_codec);
      if (HasOptions) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Options);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OutputStreamHandlerConfig other) {
      if (other == null) {
        return;
      }
      if (other.HasOutputStreamHandler) {
        OutputStreamHandler = other.OutputStreamHandler;
      }
      inputSidePacket_.Add(other.inputSidePacket_);
      if (other.HasOptions) {
        if (!HasOptions) {
          Options = new global::Akihabara.Framework.Protobuf.MediaPipeOptions();
        }
        Options.MergeFrom(other.Options);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            OutputStreamHandler = input.ReadString();
            break;
          }
          case 18: {
            inputSidePacket_.AddEntriesFrom(input, _repeated_inputSidePacket_codec);
            break;
          }
          case 26: {
            if (!HasOptions) {
              Options = new global::Akihabara.Framework.Protobuf.MediaPipeOptions();
            }
            input.ReadMessage(Options);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
