// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: test_calculators.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Akihabara.Framework.Protobuf
{

    /// <summary>Holder for reflection information generated from test_calculators.proto</summary>
    public static partial class TestCalculatorsReflection
    {

        #region Descriptor
        /// <summary>File descriptor for test_calculators.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static TestCalculatorsReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "ChZ0ZXN0X2NhbGN1bGF0b3JzLnByb3RvEiRha2loYWJhcmEuZnJhbWV3b3Jr",
                  "LnByb3RvX2NhbGN1bGF0b3IaEGNhbGN1bGF0b3IucHJvdG8ilAIKHVJhbmRv",
                  "bU1hdHJpeENhbGN1bGF0b3JPcHRpb25zEgwKBHJvd3MYASABKAUSDAoEY29s",
                  "cxgCIAEoBRIXCg9zdGFydF90aW1lc3RhbXAYAyABKAMSFwoPbGltaXRfdGlt",
                  "ZXN0YW1wGAQgASgDEhYKDnRpbWVzdGFtcF9zdGVwGAUgASgDMowBCgNleHQS",
                  "Ny5ha2loYWJhcmEuZnJhbWV3b3JrLnByb3RvX2NhbGN1bGF0b3IuQ2FsY3Vs",
                  "YXRvck9wdGlvbnMYyKDpGCABKAsyQy5ha2loYWJhcmEuZnJhbWV3b3JrLnBy",
                  "b3RvX2NhbGN1bGF0b3IuUmFuZG9tTWF0cml4Q2FsY3VsYXRvck9wdGlvbnM="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { global::Akihabara.Framework.Protobuf.CalculatorReflection.Descriptor, },
                new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Akihabara.Framework.Protobuf.RandomMatrixCalculatorOptions), global::Akihabara.Framework.Protobuf.RandomMatrixCalculatorOptions.Parser, new[]{ "Rows", "Cols", "StartTimestamp", "LimitTimestamp", "TimestampStep" }, null, null, new pb::Extension[] { global::Akihabara.Framework.Protobuf.RandomMatrixCalculatorOptions.Extensions.Ext }, null)
                }));
        }
        #endregion

    }
    #region Messages
    public sealed partial class RandomMatrixCalculatorOptions : pb::IMessage<RandomMatrixCalculatorOptions>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<RandomMatrixCalculatorOptions> _parser = new pb::MessageParser<RandomMatrixCalculatorOptions>(() => new RandomMatrixCalculatorOptions());
        private pb::UnknownFieldSet _unknownFields;
        private int _hasBits0;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<RandomMatrixCalculatorOptions> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::Akihabara.Framework.Protobuf.TestCalculatorsReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public RandomMatrixCalculatorOptions()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public RandomMatrixCalculatorOptions(RandomMatrixCalculatorOptions other) : this()
        {
            _hasBits0 = other._hasBits0;
            rows_ = other.rows_;
            cols_ = other.cols_;
            startTimestamp_ = other.startTimestamp_;
            limitTimestamp_ = other.limitTimestamp_;
            timestampStep_ = other.timestampStep_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public RandomMatrixCalculatorOptions Clone()
        {
            return new RandomMatrixCalculatorOptions(this);
        }

        /// <summary>Field number for the "rows" field.</summary>
        public const int RowsFieldNumber = 1;
        private readonly static int RowsDefaultValue = 0;

        private int rows_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Rows
        {
            get { if ((_hasBits0 & 1) != 0) { return rows_; } else { return RowsDefaultValue; } }
            set
            {
                _hasBits0 |= 1;
                rows_ = value;
            }
        }
        /// <summary>Gets whether the "rows" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasRows
        {
            get { return (_hasBits0 & 1) != 0; }
        }
        /// <summary>Clears the value of the "rows" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearRows()
        {
            _hasBits0 &= ~1;
        }

        /// <summary>Field number for the "cols" field.</summary>
        public const int ColsFieldNumber = 2;
        private readonly static int ColsDefaultValue = 0;

        private int cols_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int Cols
        {
            get { if ((_hasBits0 & 2) != 0) { return cols_; } else { return ColsDefaultValue; } }
            set
            {
                _hasBits0 |= 2;
                cols_ = value;
            }
        }
        /// <summary>Gets whether the "cols" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasCols
        {
            get { return (_hasBits0 & 2) != 0; }
        }
        /// <summary>Clears the value of the "cols" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearCols()
        {
            _hasBits0 &= ~2;
        }

        /// <summary>Field number for the "start_timestamp" field.</summary>
        public const int StartTimestampFieldNumber = 3;
        private readonly static long StartTimestampDefaultValue = 0L;

        private long startTimestamp_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long StartTimestamp
        {
            get { if ((_hasBits0 & 4) != 0) { return startTimestamp_; } else { return StartTimestampDefaultValue; } }
            set
            {
                _hasBits0 |= 4;
                startTimestamp_ = value;
            }
        }
        /// <summary>Gets whether the "start_timestamp" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasStartTimestamp
        {
            get { return (_hasBits0 & 4) != 0; }
        }
        /// <summary>Clears the value of the "start_timestamp" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearStartTimestamp()
        {
            _hasBits0 &= ~4;
        }

        /// <summary>Field number for the "limit_timestamp" field.</summary>
        public const int LimitTimestampFieldNumber = 4;
        private readonly static long LimitTimestampDefaultValue = 0L;

        private long limitTimestamp_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long LimitTimestamp
        {
            get { if ((_hasBits0 & 8) != 0) { return limitTimestamp_; } else { return LimitTimestampDefaultValue; } }
            set
            {
                _hasBits0 |= 8;
                limitTimestamp_ = value;
            }
        }
        /// <summary>Gets whether the "limit_timestamp" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasLimitTimestamp
        {
            get { return (_hasBits0 & 8) != 0; }
        }
        /// <summary>Clears the value of the "limit_timestamp" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearLimitTimestamp()
        {
            _hasBits0 &= ~8;
        }

        /// <summary>Field number for the "timestamp_step" field.</summary>
        public const int TimestampStepFieldNumber = 5;
        private readonly static long TimestampStepDefaultValue = 0L;

        private long timestampStep_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public long TimestampStep
        {
            get { if ((_hasBits0 & 16) != 0) { return timestampStep_; } else { return TimestampStepDefaultValue; } }
            set
            {
                _hasBits0 |= 16;
                timestampStep_ = value;
            }
        }
        /// <summary>Gets whether the "timestamp_step" field is set</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool HasTimestampStep
        {
            get { return (_hasBits0 & 16) != 0; }
        }
        /// <summary>Clears the value of the "timestamp_step" field</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearTimestampStep()
        {
            _hasBits0 &= ~16;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as RandomMatrixCalculatorOptions);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(RandomMatrixCalculatorOptions other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Rows != other.Rows) return false;
            if (Cols != other.Cols) return false;
            if (StartTimestamp != other.StartTimestamp) return false;
            if (LimitTimestamp != other.LimitTimestamp) return false;
            if (TimestampStep != other.TimestampStep) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (HasRows) hash ^= Rows.GetHashCode();
            if (HasCols) hash ^= Cols.GetHashCode();
            if (HasStartTimestamp) hash ^= StartTimestamp.GetHashCode();
            if (HasLimitTimestamp) hash ^= LimitTimestamp.GetHashCode();
            if (HasTimestampStep) hash ^= TimestampStep.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (HasRows) {
        output.WriteRawTag(8);
        output.WriteInt32(Rows);
      }
      if (HasCols) {
        output.WriteRawTag(16);
        output.WriteInt32(Cols);
      }
      if (HasStartTimestamp) {
        output.WriteRawTag(24);
        output.WriteInt64(StartTimestamp);
      }
      if (HasLimitTimestamp) {
        output.WriteRawTag(32);
        output.WriteInt64(LimitTimestamp);
      }
      if (HasTimestampStep) {
        output.WriteRawTag(40);
        output.WriteInt64(TimestampStep);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (HasRows)
            {
                output.WriteRawTag(8);
                output.WriteInt32(Rows);
            }
            if (HasCols)
            {
                output.WriteRawTag(16);
                output.WriteInt32(Cols);
            }
            if (HasStartTimestamp)
            {
                output.WriteRawTag(24);
                output.WriteInt64(StartTimestamp);
            }
            if (HasLimitTimestamp)
            {
                output.WriteRawTag(32);
                output.WriteInt64(LimitTimestamp);
            }
            if (HasTimestampStep)
            {
                output.WriteRawTag(40);
                output.WriteInt64(TimestampStep);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (HasRows)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rows);
            }
            if (HasCols)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(Cols);
            }
            if (HasStartTimestamp)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt64Size(StartTimestamp);
            }
            if (HasLimitTimestamp)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt64Size(LimitTimestamp);
            }
            if (HasTimestampStep)
            {
                size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimestampStep);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(RandomMatrixCalculatorOptions other)
        {
            if (other == null)
            {
                return;
            }
            if (other.HasRows)
            {
                Rows = other.Rows;
            }
            if (other.HasCols)
            {
                Cols = other.Cols;
            }
            if (other.HasStartTimestamp)
            {
                StartTimestamp = other.StartTimestamp;
            }
            if (other.HasLimitTimestamp)
            {
                LimitTimestamp = other.LimitTimestamp;
            }
            if (other.HasTimestampStep)
            {
                TimestampStep = other.TimestampStep;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Rows = input.ReadInt32();
            break;
          }
          case 16: {
            Cols = input.ReadInt32();
            break;
          }
          case 24: {
            StartTimestamp = input.ReadInt64();
            break;
          }
          case 32: {
            LimitTimestamp = input.ReadInt64();
            break;
          }
          case 40: {
            TimestampStep = input.ReadInt64();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Rows = input.ReadInt32();
                            break;
                        }
                    case 16:
                        {
                            Cols = input.ReadInt32();
                            break;
                        }
                    case 24:
                        {
                            StartTimestamp = input.ReadInt64();
                            break;
                        }
                    case 32:
                        {
                            LimitTimestamp = input.ReadInt64();
                            break;
                        }
                    case 40:
                        {
                            TimestampStep = input.ReadInt64();
                            break;
                        }
                }
            }
        }
#endif

        #region Extensions
        /// <summary>Container for extensions for other messages declared in the RandomMatrixCalculatorOptions message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Extensions
        {
            public static readonly pb::Extension<global::Akihabara.Framework.Protobuf.CalculatorOptions, global::Akihabara.Framework.Protobuf.RandomMatrixCalculatorOptions> Ext =
              new pb::Extension<global::Akihabara.Framework.Protobuf.CalculatorOptions, global::Akihabara.Framework.Protobuf.RandomMatrixCalculatorOptions>(52056136, pb::FieldCodec.ForMessage(416449090, global::Akihabara.Framework.Protobuf.RandomMatrixCalculatorOptions.Parser));
        }
        #endregion

    }

    #endregion

}

#endregion Designer generated code
